import { House } from '.';
import { ObjectId } from 'mongodb';
import { User } from './user';

export interface DB {
  users: User[];
  houses: House[];
}

export const db: DB = {
  users: [
    {
      _id: new ObjectId(),
      email: 'admin@email.com',
      password: 'test',
      salt: '',
      role: 'admin',
    },
    {
      _id: new ObjectId(),
      email: 'user@email.com',
      password: 'test',
      salt: '',
      role: 'standart-user',
    },
  ],
  houses: [
    {
      _id: '10009990',
      listing_url: 'www.casa1.es',
      name: 'Casa Rural Tereñes',
      summary: 'Summary 1',
      space: '22 mts.',
      description: 'Descripción casa Tereñes',
      neighborhood_overview: 'Varios bares y restaurantes',
      notes: 'Notas 1',
      transit: 'Transit 1',
      access: 'Para minusválidos',
      interaction: 'Interaction 1',
      house_rules: 'Prohibido fumar',
      property_type: 'property 1',
      room_type: 'Doble',
      bed_type: 'Matrimonio',
      minimum_nights: '1',
      maximum_nights: '99',
      cancellation_policy: 'media',
      last_scraped: new Date(),
      calendar_last_scraped: new Date(),
      first_review: new Date(),
      last_review: new Date(),
      accommodates: 3,
      bedrooms: 2,
      beds: 1,
      number_of_reviews: 0,
      bathrooms: 1,
      amenities: ['cepillo', 'jabón'],
      price: 80,
      security_deposit: 200,
      cleaning_fee: 0,
      extra_people: 2,
      guests_included: 1,
      images: {},
      host: {},
      address: {
        country: 'España',
        country_code: 'ES',
      },
      availalability: {},
      review_scores: {},
      reviews: [
        { name: 'Review 1', comment: 'Commentario 1', date: new Date() },
        { name: 'Review 2', comment: 'Commentario 2', date: new Date() },
      ],
    },
    {
      _id: '10009991',
      listing_url: 'www.casa2.es',
      name: 'Casa Rural La Cueste',
      summary: 'Summary 2',
      space: '26 mts.',
      description: 'Descripción casa La Cueste',
      neighborhood_overview: 'Varios bares y restaurantes',
      notes: 'Notas 2',
      transit: 'Transit 2',
      access: 'Para minusválidos',
      interaction: 'Interaction 2',
      house_rules: 'Prohibido fumar',
      property_type: 'property 2',
      room_type: 'Doble',
      bed_type: 'Matrimonio',
      minimum_nights: '1',
      maximum_nights: '99',
      cancellation_policy: 'media',
      last_scraped: new Date(),
      calendar_last_scraped: new Date(),
      first_review: new Date(),
      last_review: new Date(),
      accommodates: 3,
      bedrooms: 2,
      beds: 1,
      number_of_reviews: 0,
      bathrooms: 1,
      amenities: ['cepillo', 'jabón'],
      price: 80,
      security_deposit: 200,
      cleaning_fee: 0,
      extra_people: 2,
      guests_included: 1,
      images: {},
      host: {},
      address: {
        country: 'Portugal',
        country_code: 'PT',
      },
      availalability: {},
      review_scores: {},
      reviews: [
        { name: 'Review 1', comment: 'Commentario 1', date: new Date() },
        { name: 'Review 2', comment: 'Commentario 2', date: new Date() },
      ],
    },
  ],
};
