version: '3.8'
services:
  mongo:
    container_name: mongo-db
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - './mongo-data:/data/db'
volumes:
  misdatosmongo:
    external: true
    name: misdatosmongo
